import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function CustomerDetails(setCustomerDetailsStage, setShippingDetailsStage, setCustomerForOrder, firstName, setFirstName, lastName, setLastName, email, setEmail, telegram, setTelegram, cancelButton) {
    return (_jsx("form", Object.assign({ onSubmit: (e) => {
            e.preventDefault();
            setCustomerDetailsStage(false);
            setShippingDetailsStage(true);
            setCustomerForOrder();
        } }, { children: _jsxs("div", Object.assign({ className: "form-row" }, { children: [_jsxs("div", Object.assign({ className: "form-group col-md-6" }, { children: [_jsx("label", Object.assign({ htmlFor: "inputFirstName4" }, { children: "First Name" })), _jsx("input", { required: true, onChange: event => setFirstName(event.target.value), value: firstName, name: 'firstName', type: "text", id: "inputFirstName4", className: "form-control", placeholder: "First name" })] })), _jsxs("div", Object.assign({ className: "form-group col-md-6" }, { children: [_jsx("label", Object.assign({ htmlFor: "inputLastName4" }, { children: "Last Name" })), _jsx("input", { required: true, onChange: event => setLastName(event.target.value), value: lastName, name: 'lastName', type: "text", className: "form-control", placeholder: "Last name" })] })), _jsxs("div", Object.assign({ className: "form-group col-md-6" }, { children: [_jsx("label", Object.assign({ htmlFor: "inputEmail4" }, { children: "Email" })), _jsx("input", { required: true, onChange: event => setEmail(event.target.value), value: email, type: "email", className: "form-control", id: "inputEmail4", placeholder: "Email" })] })), _jsxs("div", Object.assign({ className: "form-group col-md-6" }, { children: [_jsx("label", Object.assign({ htmlFor: "inputTelegram4" }, { children: "Telegram" })), _jsx("input", { required: true, onChange: event => setTelegram(event.target.value), value: telegram, type: "telegram", className: "form-control", id: "inputTelegram4", placeholder: "Telegram" })] })), _jsxs("div", Object.assign({ className: "form-group col-md-12 d-flex justify-content-between" }, { children: [cancelButton(), _jsx("button", Object.assign({ className: 'my-button small' }, { children: "Next" }))] }))] })) })));
}
export default CustomerDetails;
