"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
function CustomerDetails(setCustomerDetailsStage, setShippingDetailsStage, setCustomerForOrder, firstName, setFirstName, lastName, setLastName, email, setEmail, telegram, setTelegram, cancelButton) {
    return ((0, jsx_runtime_1.jsx)("form", Object.assign({ onSubmit: (e) => {
            e.preventDefault();
            setCustomerDetailsStage(false);
            setShippingDetailsStage(true);
            setCustomerForOrder();
        } }, { children: (0, jsx_runtime_1.jsxs)("div", Object.assign({ className: "form-row" }, { children: [(0, jsx_runtime_1.jsxs)("div", Object.assign({ className: "form-group col-md-6" }, { children: [(0, jsx_runtime_1.jsx)("label", Object.assign({ htmlFor: "inputFirstName4" }, { children: "First Name" })), (0, jsx_runtime_1.jsx)("input", { required: true, onChange: event => setFirstName(event.target.value), value: firstName, name: 'firstName', type: "text", id: "inputFirstName4", className: "form-control", placeholder: "First name" })] })), (0, jsx_runtime_1.jsxs)("div", Object.assign({ className: "form-group col-md-6" }, { children: [(0, jsx_runtime_1.jsx)("label", Object.assign({ htmlFor: "inputLastName4" }, { children: "Last Name" })), (0, jsx_runtime_1.jsx)("input", { required: true, onChange: event => setLastName(event.target.value), value: lastName, name: 'lastName', type: "text", className: "form-control", placeholder: "Last name" })] })), (0, jsx_runtime_1.jsxs)("div", Object.assign({ className: "form-group col-md-6" }, { children: [(0, jsx_runtime_1.jsx)("label", Object.assign({ htmlFor: "inputEmail4" }, { children: "Email" })), (0, jsx_runtime_1.jsx)("input", { required: true, onChange: event => setEmail(event.target.value), value: email, type: "email", className: "form-control", id: "inputEmail4", placeholder: "Email" })] })), (0, jsx_runtime_1.jsxs)("div", Object.assign({ className: "form-group col-md-6" }, { children: [(0, jsx_runtime_1.jsx)("label", Object.assign({ htmlFor: "inputTelegram4" }, { children: "Telegram" })), (0, jsx_runtime_1.jsx)("input", { required: true, onChange: event => setTelegram(event.target.value), value: telegram, type: "telegram", className: "form-control", id: "inputTelegram4", placeholder: "Telegram" })] })), (0, jsx_runtime_1.jsxs)("div", Object.assign({ className: "form-group col-md-12 d-flex justify-content-between" }, { children: [cancelButton(), (0, jsx_runtime_1.jsx)("button", Object.assign({ className: 'my-button small' }, { children: "Next" }))] }))] })) })));
}
exports.default = CustomerDetails;
