import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function ReviewDetails(activeOrderData, transitionToPayment, setShippingAddress, setPaymentStage, setCustomerPaysStage, cancelButton, editButton) {
    return (_jsxs("div", { children: [_jsxs("div", Object.assign({ className: 'row' }, { children: [_jsxs("div", Object.assign({ className: 'col-md-12 col-lg-6 d-flex flex-column pl-lg-4 pb-3' }, { children: [_jsx("h3", { children: "SHIPPING INFO" }), _jsx("p", Object.assign({ className: 'pb-0 mb-0' }, { children: activeOrderData.activeOrder.shippingAddress.fullName })), _jsx("p", Object.assign({ className: 'pb-0 mb-0' }, { children: activeOrderData.activeOrder.shippingAddress.streetLine1 })), _jsx("p", Object.assign({ className: 'pb-0 mb-0' }, { children: activeOrderData.activeOrder.shippingAddress.streetLine2 })), _jsx("p", Object.assign({ className: 'pb-0 mb-0' }, { children: `${activeOrderData.activeOrder.shippingAddress.city}, ${activeOrderData.activeOrder.shippingAddress.postalCode}` })), _jsx("p", Object.assign({ className: 'pb-0 mb-0' }, { children: `${activeOrderData.activeOrder.shippingAddress.province} - ${activeOrderData.activeOrder.shippingAddress.country}` }))] })), _jsxs("div", Object.assign({ className: 'col-md-12 col-lg-6 text-lg-right text-md-left d-flex flex-column' }, { children: [_jsx("h3", { children: "CONTACT" }), _jsx("p", Object.assign({ className: 'pb-0 mb-0' }, { children: activeOrderData.activeOrder.shippingAddress.company })), _jsx("p", Object.assign({ className: 'pb-0 mb-0' }, { children: activeOrderData.activeOrder.shippingAddress.phoneNumber })), _jsxs("p", Object.assign({ className: 'mt-2' }, { children: ["Payment with: ", activeOrderData.activeOrder.shippingAddress.customFields.paymentType] }))] }))] })), _jsxs("div", Object.assign({ className: 'text-center d-flex flex-column text-center' }, { children: [_jsx("div", { children: _jsx("button", Object.assign({ style: { margin: '5px' }, type: 'button', className: 'my-button', onClick: e => {
                                transitionToPayment();
                                setShippingAddress();
                                // console.log('Zmiana na arranging payment POSZLA!')
                                setPaymentStage(false);
                                setCustomerPaysStage(true);
                            } }, { children: "FINALIZE AND PAY!" })) }), _jsxs("div", { children: [_jsxs("span", Object.assign({ style: { margin: '2.5px' } }, { children: [" ", cancelButton(), " "] })), _jsxs("span", Object.assign({ style: { margin: '2.5px' } }, { children: [" ", editButton(setPaymentStage), " "] }))] })] }))] }));
}
export default ReviewDetails;
